name: Build Docker Image

on:
  workflow_run:
    workflows: ["rust.yml"] # Using filename as identifier as rust.yml was not found
    types: [completed]
    branches: [main]

jobs:
  build_and_push_sha_tagged_image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # This sets up QEMU for multi-platform builds

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64 # Added platforms for multi-arch build
          tags: ghcr.io/wizardsupreme/docs-mcp:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max