name: Release Docker Image and Create GitHub Release

on:
  workflow_run:
    workflows: ["Build Docker Image"]
    types: [completed]
    branches: [main]
  push:
    tags:
      - 'v*'

jobs:
  release_and_publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    permissions:
      contents: write # For checkout (read) and gh-release (write)
      packages: write # For docker push to GHCR
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Recommended for full history for release notes/metadata

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/wizardsupreme/docs-mcp
          tags: |
            # For workflow_run on main branch, tag as latest
            type=raw,value=latest,enable=${{ github.event_name == 'workflow_run' && github.ref_name == 'main' }}
            # For git v* tags, use the tag itself (e.g., v1.2.3 -> 1.2.3 from {{version}}, and v1.2 -> 1.2 from {{major}}.{{minor}})
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            # Also tag v* tags as 'latest'
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: "Release for version ${{ github.ref_name }}. Docker image pushed to ghcr.io/wizardsupreme/docs-mcp:${{ steps.meta.outputs.version }} and ghcr.io/wizardsupreme/docs-mcp:latest."
          draft: false
          prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}